#!/bin/bash
ln -s ~/dotfiles/zshrc ~/.zshrc 
ln -s ~/dotfiles/vim ~/.vim 
ln -s ~/dotfiles/vimrc ~/.vimrc 
ln -s ~/dotfiles/zprezto ~/.zprezto  
ln -s ~/dotfiles/zpreztorc ~/.zpreztorc
ln -s ~/dotfiles/psqlrc ~/.psqlrc
ln -s ~/dotfiles/tmux-conf ~/.tmux-conf
ln -s ~/dotfiles/emacs.d ~/.emacs.d

