#!/bin/bash
ln -sf ~/dotfiles/zshrc ~/.zshrc 
ln -sf ~/dotfiles/vim ~/.vim 
ln -sf ~/dotfiles/vimrc ~/.vimrc 
ln -sf ~/dotfiles/zprezto ~/.zprezto  
ln -sf ~/dotfiles/zpreztorc ~/.zpreztorc
ln -sf ~/dotfiles/psqlrc ~/.psqlrc
ln -sf ~/dotfiles/tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/emacs.d ~/.emacs.d
ln -sf ~/dotfiles/dotemacs ~/.emacs
ln -sf ~/dotfiles/zsh-autosuggestions ~/.zsh-autosuggestions
ln -sf ~/dotfiles/irssi ~/.irssi
