(deftheme gotham-david
  "Created 2017-03-14.")

(custom-theme-set-faces
 'gotham-david
 '(default ((t (:inherit nil :stipple nil :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
 '(cursor ((t (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "brightred"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "cyan"))))
 '(highlight ((t (:foreground "orange" :background "brightgreen"))))
 '(region ((t (:background "brightblue"))))
 '(shadow ((t (:foreground "brightyellow"))))
 '(secondary-selection ((t (:background "magenta"))))
 '(trailing-whitespace ((t (:foreground "#FFFFFF" :background "red"))))
 '(font-lock-builtin-face ((t (:foreground "brightred"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "brightyellow"))))
 '(font-lock-comment-face ((t (:foreground "brightyellow"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "cyan"))))
 '(font-lock-doc-face ((t (:foreground "green"))))
 '(font-lock-function-name-face ((t (:foreground "brightcyan"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "blue"))))
 '(font-lock-negation-char-face ((t (:foreground "red"))))
 '(font-lock-preprocessor-face ((t (:foreground "red"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "yellow"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "yellow"))))
 '(font-lock-string-face ((t (:foreground "green"))))
 '(font-lock-type-face ((t (:foreground "brightred"))))
 '(font-lock-variable-name-face ((t (:foreground "brightcyan"))))
 '(font-lock-warning-face ((t (:foreground "red"))))
 '(button ((t (:underline (:color foreground-color :style line) :box (:line-width 1 :color nil :style nil) :foreground "brightyellow" :background "#444444" :inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "brightred"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "yellow" :inherit (link)))))
 '(fringe ((t (:foreground "white" :background "brightblack"))))
 '(header-line ((t (:box nil :foreground "brightcyan" :background "brightgreen" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "white" :background "black" :inherit (variable-pitch)))))
 '(mode-line ((t (:box nil :foreground "brightcyan" :background "brightgreen"))))
 '(mode-line-buffer-id ((t (:weight bold :box nil))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box nil :foreground "white"))))
 '(mode-line-inactive ((t (:weight light :box nil :foreground "brightyellow" :background "brightblack" :inherit (mode-line)))))
 '(isearch ((t (:inverse-video t :foreground "#000" :background "#fff"))))
 '(isearch-fail ((t (:foreground "red" :background "#ffaaaa"))))
 '(lazy-highlight ((t (:foreground "brightgreen" :background "yellow"))))
 '(match ((t (:background "brightcyan"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'gotham-david)
